# Generated by Django 4.1.5 on 2023-01-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_master_user_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('release_id', models.IntegerField()),
            ],
        ),
    ]
