# Generated by Django 4.1.5 on 2023-01-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_testoffer"),
    ]

    operations = [
        migrations.DeleteModel(name="TestOffer",),
        migrations.AddField(
            model_name="offer",
            name="url",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
