# Generated by Django 4.1.5 on 2023-01-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_delete_testoffer_offer_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="master", name="image_url",),
    ]
